; Listing generated by Microsoft (R) Optimizing Compiler Version 19.29.30145.0 

include listing.inc

INCLUDELIB OLDNAMES

PUBLIC	??_R2AllPassFilter@@8				; AllPassFilter::`RTTI Base Class Array'
PUBLIC	??_R0?AVAllPassFilter@@@8			; AllPassFilter `RTTI Type Descriptor'
PUBLIC	??_R4AllPassFilter@@6B@				; AllPassFilter::`RTTI Complete Object Locator'
PUBLIC	??_R1A@?0A@EA@Delay@@8				; Delay::`RTTI Base Class Descriptor at (0,-1,0,64)'
PUBLIC	??_7AllPassFilter@@6B@				; AllPassFilter::`vftable'
PUBLIC	??_R3Delay@@8					; Delay::`RTTI Class Hierarchy Descriptor'
PUBLIC	??_R1A@?0A@EA@AllPassFilter@@8			; AllPassFilter::`RTTI Base Class Descriptor at (0,-1,0,64)'
PUBLIC	??_R0?AVDelay@@@8				; Delay `RTTI Type Descriptor'
PUBLIC	??_R3AllPassFilter@@8				; AllPassFilter::`RTTI Class Hierarchy Descriptor'
PUBLIC	??_R2Delay@@8					; Delay::`RTTI Base Class Array'
EXTRN	??_7type_info@@6B@:BYTE				; type_info::`vftable'
EXTRN	__imp_pow:PROC
EXTRN	__imp___std_terminate:PROC
EXTRN	__imp___CxxFrameHandler4:PROC
;	COMDAT ??_R2Delay@@8
rdata$r	SEGMENT
??_R2Delay@@8 DD imagerel ??_R1A@?0A@EA@Delay@@8	; Delay::`RTTI Base Class Array'
	ORG $+3
rdata$r	ENDS
;	COMDAT ??_R3AllPassFilter@@8
rdata$r	SEGMENT
??_R3AllPassFilter@@8 DD 00H				; AllPassFilter::`RTTI Class Hierarchy Descriptor'
	DD	00H
	DD	02H
	DD	imagerel ??_R2AllPassFilter@@8
rdata$r	ENDS
;	COMDAT ??_R0?AVDelay@@@8
data$rs	SEGMENT
??_R0?AVDelay@@@8 DQ FLAT:??_7type_info@@6B@		; Delay `RTTI Type Descriptor'
	DQ	0000000000000000H
	DB	'.?AVDelay@@', 00H
data$rs	ENDS
;	COMDAT ??_R1A@?0A@EA@AllPassFilter@@8
rdata$r	SEGMENT
??_R1A@?0A@EA@AllPassFilter@@8 DD imagerel ??_R0?AVAllPassFilter@@@8 ; AllPassFilter::`RTTI Base Class Descriptor at (0,-1,0,64)'
	DD	01H
	DD	00H
	DD	0ffffffffH
	DD	00H
	DD	040H
	DD	imagerel ??_R3AllPassFilter@@8
rdata$r	ENDS
;	COMDAT ??_R3Delay@@8
rdata$r	SEGMENT
??_R3Delay@@8 DD 00H					; Delay::`RTTI Class Hierarchy Descriptor'
	DD	00H
	DD	01H
	DD	imagerel ??_R2Delay@@8
rdata$r	ENDS
;	COMDAT ??_7AllPassFilter@@6B@
CONST	SEGMENT
??_7AllPassFilter@@6B@ DQ FLAT:??_R4AllPassFilter@@6B@	; AllPassFilter::`vftable'
	DQ	FLAT:?init@Delay@@UEAAXMH@Z
	DQ	FLAT:?setSampleRate@Delay@@UEAAXH@Z
	DQ	FLAT:?processAudio@AllPassFilter@@UEAAMM@Z
CONST	ENDS
;	COMDAT ??_R1A@?0A@EA@Delay@@8
rdata$r	SEGMENT
??_R1A@?0A@EA@Delay@@8 DD imagerel ??_R0?AVDelay@@@8	; Delay::`RTTI Base Class Descriptor at (0,-1,0,64)'
	DD	00H
	DD	00H
	DD	0ffffffffH
	DD	00H
	DD	040H
	DD	imagerel ??_R3Delay@@8
rdata$r	ENDS
;	COMDAT ??_R4AllPassFilter@@6B@
rdata$r	SEGMENT
??_R4AllPassFilter@@6B@ DD 01H				; AllPassFilter::`RTTI Complete Object Locator'
	DD	00H
	DD	00H
	DD	imagerel ??_R0?AVAllPassFilter@@@8
	DD	imagerel ??_R3AllPassFilter@@8
	DD	imagerel ??_R4AllPassFilter@@6B@
rdata$r	ENDS
;	COMDAT ??_R0?AVAllPassFilter@@@8
data$rs	SEGMENT
??_R0?AVAllPassFilter@@@8 DQ FLAT:??_7type_info@@6B@	; AllPassFilter `RTTI Type Descriptor'
	DQ	0000000000000000H
	DB	'.?AVAllPassFilter@@', 00H
data$rs	ENDS
;	COMDAT ??_R2AllPassFilter@@8
rdata$r	SEGMENT
??_R2AllPassFilter@@8 DD imagerel ??_R1A@?0A@EA@AllPassFilter@@8 ; AllPassFilter::`RTTI Base Class Array'
	DD	imagerel ??_R1A@?0A@EA@Delay@@8
	ORG $+3
rdata$r	ENDS
PUBLIC	?processAudio@AllPassFilter@@UEAAMM@Z		; AllPassFilter::processAudio
PUBLIC	?setFeedback@AllPassFilter@@QEAAXM@Z		; AllPassFilter::setFeedback
PUBLIC	??1AllPassFilter@@QEAA@XZ			; AllPassFilter::~AllPassFilter
PUBLIC	??0AllPassFilter@@QEAA@XZ			; AllPassFilter::AllPassFilter
PUBLIC	__real@00000000
PUBLIC	__real@0000000000000000
PUBLIC	__real@3a83126f
PUBLIC	__real@3b03126f
PUBLIC	__real@3d4ccccd
PUBLIC	__real@3d888889
PUBLIC	__real@3ee4f8b588e368f1
PUBLIC	__real@3f000000
PUBLIC	__real@3f5921fb54442d18
PUBLIC	__real@3f59999a
PUBLIC	__real@3f7d70a4
PUBLIC	__real@3f800000
PUBLIC	__real@3f969696
PUBLIC	__real@3fb447c30d306a2b
PUBLIC	__real@3fb5555555555555
PUBLIC	__real@3fb999999999999a
PUBLIC	__real@3fdaaaaaaaaaaaab
PUBLIC	__real@3fdb1633482be8bc
PUBLIC	__real@3fdd70a3d70a3d71
PUBLIC	__real@3fdfd7dbf487fcb9
PUBLIC	__real@3fe0000000000000
PUBLIC	__real@3fe147ae147ae148
PUBLIC	__real@3fefae147ae147ae
PUBLIC	__real@3ff0000000000000
PUBLIC	__real@40000000
PUBLIC	__real@4000000000000000
PUBLIC	__real@400921fb54442d18
PUBLIC	__real@4010000000000000
PUBLIC	__real@401921fb54442d18
PUBLIC	__real@4024000000000000
PUBLIC	__real@4028000000000000
PUBLIC	__real@4034000000000000
PUBLIC	__real@4038000000000000
PUBLIC	__real@4040000000000000
PUBLIC	__real@40affe0000000000
PUBLIC	__real@40b0000000000000
PUBLIC	__real@40c00000
PUBLIC	__real@40d09a0000000000
PUBLIC	__real@40d28e0000000000
PUBLIC	__real@40d3880000000000
PUBLIC	__real@40e00000
PUBLIC	__real@41200000
PUBLIC	__real@41480000
PUBLIC	__real@416312cfe0000000
PUBLIC	__real@41700000
PUBLIC	__real@4197d783fc000000
PUBLIC	__real@41a00000
PUBLIC	__real@42480000
PUBLIC	__real@42c80000
PUBLIC	__real@43960000
PUBLIC	__real@43e0000000000000
PUBLIC	__real@43fa0000
PUBLIC	__real@447a0000
PUBLIC	__real@45000000
PUBLIC	__real@46944800
PUBLIC	__real@bb449ba6
PUBLIC	__real@c003333333333333
PUBLIC	__real@c01921fb54442d18
PUBLIC	__xmm@80000000000000008000000000000000
EXTRN	__CxxFrameHandler4:PROC
EXTRN	__chkstk:PROC
EXTRN	memset:PROC
EXTRN	__ImageBase:BYTE
EXTRN	_fltused:DWORD
;	COMDAT pdata
pdata	SEGMENT
$pdata$?processAudio@AllPassFilter@@UEAAMM@Z DD imagerel $LN10
	DD	imagerel $LN10+94
	DD	imagerel $unwind$?processAudio@AllPassFilter@@UEAAMM@Z
;	COMDAT __xmm@80000000000000008000000000000000
CONST	SEGMENT
__xmm@80000000000000008000000000000000 DB 00H, 00H, 00H, 00H, 00H, 00H, 00H
	DB	080H, 00H, 00H, 00H, 00H, 00H, 00H, 00H, 080H
CONST	ENDS
;	COMDAT __real@c01921fb54442d18
CONST	SEGMENT
__real@c01921fb54442d18 DQ 0c01921fb54442d18r	; -6.28319
CONST	ENDS
;	COMDAT __real@c003333333333333
CONST	SEGMENT
__real@c003333333333333 DQ 0c003333333333333r	; -2.4
CONST	ENDS
;	COMDAT __real@bb449ba6
CONST	SEGMENT
__real@bb449ba6 DD 0bb449ba6r			; -0.003
CONST	ENDS
;	COMDAT __real@46944800
CONST	SEGMENT
__real@46944800 DD 046944800r			; 18980
CONST	ENDS
;	COMDAT __real@45000000
CONST	SEGMENT
__real@45000000 DD 045000000r			; 2048
CONST	ENDS
;	COMDAT __real@447a0000
CONST	SEGMENT
__real@447a0000 DD 0447a0000r			; 1000
CONST	ENDS
;	COMDAT __real@43fa0000
CONST	SEGMENT
__real@43fa0000 DD 043fa0000r			; 500
CONST	ENDS
;	COMDAT __real@43e0000000000000
CONST	SEGMENT
__real@43e0000000000000 DQ 043e0000000000000r	; 9.22337e+18
CONST	ENDS
;	COMDAT __real@43960000
CONST	SEGMENT
__real@43960000 DD 043960000r			; 300
CONST	ENDS
;	COMDAT __real@42c80000
CONST	SEGMENT
__real@42c80000 DD 042c80000r			; 100
CONST	ENDS
;	COMDAT __real@42480000
CONST	SEGMENT
__real@42480000 DD 042480000r			; 50
CONST	ENDS
;	COMDAT __real@41a00000
CONST	SEGMENT
__real@41a00000 DD 041a00000r			; 20
CONST	ENDS
;	COMDAT __real@4197d783fc000000
CONST	SEGMENT
__real@4197d783fc000000 DQ 04197d783fc000000r	; 1e+08
CONST	ENDS
;	COMDAT __real@41700000
CONST	SEGMENT
__real@41700000 DD 041700000r			; 15
CONST	ENDS
;	COMDAT __real@416312cfe0000000
CONST	SEGMENT
__real@416312cfe0000000 DQ 0416312cfe0000000r	; 1e+07
CONST	ENDS
;	COMDAT __real@41480000
CONST	SEGMENT
__real@41480000 DD 041480000r			; 12.5
CONST	ENDS
;	COMDAT __real@41200000
CONST	SEGMENT
__real@41200000 DD 041200000r			; 10
CONST	ENDS
;	COMDAT __real@40e00000
CONST	SEGMENT
__real@40e00000 DD 040e00000r			; 7
CONST	ENDS
;	COMDAT __real@40d3880000000000
CONST	SEGMENT
__real@40d3880000000000 DQ 040d3880000000000r	; 20000
CONST	ENDS
;	COMDAT __real@40d28e0000000000
CONST	SEGMENT
__real@40d28e0000000000 DQ 040d28e0000000000r	; 19000
CONST	ENDS
;	COMDAT __real@40d09a0000000000
CONST	SEGMENT
__real@40d09a0000000000 DQ 040d09a0000000000r	; 17000
CONST	ENDS
;	COMDAT __real@40c00000
CONST	SEGMENT
__real@40c00000 DD 040c00000r			; 6
CONST	ENDS
;	COMDAT __real@40b0000000000000
CONST	SEGMENT
__real@40b0000000000000 DQ 040b0000000000000r	; 4096
CONST	ENDS
;	COMDAT __real@40affe0000000000
CONST	SEGMENT
__real@40affe0000000000 DQ 040affe0000000000r	; 4095
CONST	ENDS
;	COMDAT __real@4040000000000000
CONST	SEGMENT
__real@4040000000000000 DQ 04040000000000000r	; 32
CONST	ENDS
;	COMDAT __real@4038000000000000
CONST	SEGMENT
__real@4038000000000000 DQ 04038000000000000r	; 24
CONST	ENDS
;	COMDAT __real@4034000000000000
CONST	SEGMENT
__real@4034000000000000 DQ 04034000000000000r	; 20
CONST	ENDS
;	COMDAT __real@4028000000000000
CONST	SEGMENT
__real@4028000000000000 DQ 04028000000000000r	; 12
CONST	ENDS
;	COMDAT __real@4024000000000000
CONST	SEGMENT
__real@4024000000000000 DQ 04024000000000000r	; 10
CONST	ENDS
;	COMDAT __real@401921fb54442d18
CONST	SEGMENT
__real@401921fb54442d18 DQ 0401921fb54442d18r	; 6.28319
CONST	ENDS
;	COMDAT __real@4010000000000000
CONST	SEGMENT
__real@4010000000000000 DQ 04010000000000000r	; 4
CONST	ENDS
;	COMDAT __real@400921fb54442d18
CONST	SEGMENT
__real@400921fb54442d18 DQ 0400921fb54442d18r	; 3.14159
CONST	ENDS
;	COMDAT __real@4000000000000000
CONST	SEGMENT
__real@4000000000000000 DQ 04000000000000000r	; 2
CONST	ENDS
;	COMDAT __real@40000000
CONST	SEGMENT
__real@40000000 DD 040000000r			; 2
CONST	ENDS
;	COMDAT __real@3ff0000000000000
CONST	SEGMENT
__real@3ff0000000000000 DQ 03ff0000000000000r	; 1
CONST	ENDS
;	COMDAT __real@3fefae147ae147ae
CONST	SEGMENT
__real@3fefae147ae147ae DQ 03fefae147ae147aer	; 0.99
CONST	ENDS
;	COMDAT __real@3fe147ae147ae148
CONST	SEGMENT
__real@3fe147ae147ae148 DQ 03fe147ae147ae148r	; 0.54
CONST	ENDS
;	COMDAT __real@3fe0000000000000
CONST	SEGMENT
__real@3fe0000000000000 DQ 03fe0000000000000r	; 0.5
CONST	ENDS
;	COMDAT __real@3fdfd7dbf487fcb9
CONST	SEGMENT
__real@3fdfd7dbf487fcb9 DQ 03fdfd7dbf487fcb9r	; 0.49755
CONST	ENDS
;	COMDAT __real@3fdd70a3d70a3d71
CONST	SEGMENT
__real@3fdd70a3d70a3d71 DQ 03fdd70a3d70a3d71r	; 0.46
CONST	ENDS
;	COMDAT __real@3fdb1633482be8bc
CONST	SEGMENT
__real@3fdb1633482be8bc DQ 03fdb1633482be8bcr	; 0.42323
CONST	ENDS
;	COMDAT __real@3fdaaaaaaaaaaaab
CONST	SEGMENT
__real@3fdaaaaaaaaaaaab DQ 03fdaaaaaaaaaaaabr	; 0.416667
CONST	ENDS
;	COMDAT __real@3fb999999999999a
CONST	SEGMENT
__real@3fb999999999999a DQ 03fb999999999999ar	; 0.1
CONST	ENDS
;	COMDAT __real@3fb5555555555555
CONST	SEGMENT
__real@3fb5555555555555 DQ 03fb5555555555555r	; 0.0833333
CONST	ENDS
;	COMDAT __real@3fb447c30d306a2b
CONST	SEGMENT
__real@3fb447c30d306a2b DQ 03fb447c30d306a2br	; 0.07922
CONST	ENDS
;	COMDAT __real@3f969696
CONST	SEGMENT
__real@3f969696 DD 03f969696r			; 1.17647
CONST	ENDS
;	COMDAT __real@3f800000
CONST	SEGMENT
__real@3f800000 DD 03f800000r			; 1
CONST	ENDS
;	COMDAT __real@3f7d70a4
CONST	SEGMENT
__real@3f7d70a4 DD 03f7d70a4r			; 0.99
CONST	ENDS
;	COMDAT __real@3f59999a
CONST	SEGMENT
__real@3f59999a DD 03f59999ar			; 0.85
CONST	ENDS
;	COMDAT __real@3f5921fb54442d18
CONST	SEGMENT
__real@3f5921fb54442d18 DQ 03f5921fb54442d18r	; 0.00153398
CONST	ENDS
;	COMDAT __real@3f000000
CONST	SEGMENT
__real@3f000000 DD 03f000000r			; 0.5
CONST	ENDS
;	COMDAT __real@3ee4f8b588e368f1
CONST	SEGMENT
__real@3ee4f8b588e368f1 DQ 03ee4f8b588e368f1r	; 1e-05
CONST	ENDS
;	COMDAT __real@3d888889
CONST	SEGMENT
__real@3d888889 DD 03d888889r			; 0.0666667
CONST	ENDS
;	COMDAT __real@3d4ccccd
CONST	SEGMENT
__real@3d4ccccd DD 03d4ccccdr			; 0.05
CONST	ENDS
;	COMDAT __real@3b03126f
CONST	SEGMENT
__real@3b03126f DD 03b03126fr			; 0.002
CONST	ENDS
;	COMDAT __real@3a83126f
CONST	SEGMENT
__real@3a83126f DD 03a83126fr			; 0.001
CONST	ENDS
;	COMDAT __real@0000000000000000
CONST	SEGMENT
__real@0000000000000000 DQ 00000000000000000r	; 0
CONST	ENDS
;	COMDAT __real@00000000
CONST	SEGMENT
__real@00000000 DD 000000000r			; 0
CONST	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?processAudio@AllPassFilter@@UEAAMM@Z DD 010401H
	DD	04204H
xdata	ENDS
; Function compile flags: /Ogspy
; File C:\Users\RenatoVolpe\personal\fox-suite-blocks\src\AllPassFilter.cpp
; File C:\Users\RenatoVolpe\personal\fox-suite-blocks\src\Delay.cpp
; File C:\Users\RenatoVolpe\personal\fox-suite-blocks\src\AllPassFilter.cpp
; File C:\Users\RenatoVolpe\personal\fox-suite-blocks\src\Delay.cpp
; File C:\Users\RenatoVolpe\personal\fox-suite-blocks\src\AllPassFilter.cpp
; File C:\Users\RenatoVolpe\personal\fox-suite-blocks\src\Delay.cpp
; File C:\Users\RenatoVolpe\personal\fox-suite-blocks\src\AllPassFilter.cpp
;	COMDAT ??0AllPassFilter@@QEAA@XZ
_TEXT	SEGMENT
this$ = 8
??0AllPassFilter@@QEAA@XZ PROC				; AllPassFilter::AllPassFilter, COMDAT
; File C:\Users\RenatoVolpe\personal\fox-suite-blocks\src\Delay.cpp

; 8    : 	dly_buffer				= NULL;

	xor	edx, edx

; 10   : 	dly_makeUpGain			= 1.0;

	mov	QWORD PTR [rcx+52], 1065353216		; 3f800000H
; File C:\Users\RenatoVolpe\personal\fox-suite-blocks\src\AllPassFilter.cpp

; 5    : AllPassFilter::AllPassFilter() : Delay() {

	lea	rax, OFFSET FLAT:??_7AllPassFilter@@6B@
; File C:\Users\RenatoVolpe\personal\fox-suite-blocks\src\Delay.cpp

; 8    : 	dly_buffer				= NULL;

	mov	QWORD PTR [rcx+40], rdx
; File C:\Users\RenatoVolpe\personal\fox-suite-blocks\src\AllPassFilter.cpp

; 5    : AllPassFilter::AllPassFilter() : Delay() {

	mov	QWORD PTR [rcx], rax

; 8    : }

	mov	rax, rcx
; File C:\Users\RenatoVolpe\personal\fox-suite-blocks\src\Delay.cpp

; 9    : 	dly_makeUpGaindB		= 0.0;

	mov	DWORD PTR [rcx+48], edx

; 11   : 	dly_delayInmsec			= 0.0;
; 12   : 	dly_delayInSamples		= 0.0;

	mov	QWORD PTR [rcx+20], rdx

; 13   : 	dly_readIndex			= 0;

	mov	QWORD PTR [rcx+28], rdx

; 14   : 	dly_writeIndex			= 0;
; 15   : 	dly_lineLengthInSamples = 0;

	mov	QWORD PTR [rcx+12], rdx
; File C:\Users\RenatoVolpe\personal\fox-suite-blocks\src\AllPassFilter.cpp

; 7    : 	ap_decayInSeconds = 0.0;

	mov	DWORD PTR [rcx+60], edx

; 8    : }

	ret	0
??0AllPassFilter@@QEAA@XZ ENDP				; AllPassFilter::AllPassFilter
_TEXT	ENDS
; Function compile flags: /Ogspy
; File C:\Users\RenatoVolpe\personal\fox-suite-blocks\src\AllPassFilter.cpp
;	COMDAT ??1AllPassFilter@@QEAA@XZ
_TEXT	SEGMENT
this$ = 8
??1AllPassFilter@@QEAA@XZ PROC				; AllPassFilter::~AllPassFilter, COMDAT

; 10   : AllPassFilter::~AllPassFilter() {}

	lea	rax, OFFSET FLAT:??_7AllPassFilter@@6B@
	mov	QWORD PTR [rcx], rax
	jmp	??1Delay@@QEAA@XZ			; Delay::~Delay
??1AllPassFilter@@QEAA@XZ ENDP				; AllPassFilter::~AllPassFilter
_TEXT	ENDS
; Function compile flags: /Ogspy
; File C:\Users\RenatoVolpe\personal\fox-suite-blocks\src\AllPassFilter.cpp
;	COMDAT ?setFeedback@AllPassFilter@@QEAAXM@Z
_TEXT	SEGMENT
this$ = 8
g$ = 16
?setFeedback@AllPassFilter@@QEAAXM@Z PROC		; AllPassFilter::setFeedback, COMDAT

; 14   : 	ap_feedbackGain = g;	

	movss	DWORD PTR [rcx+56], xmm1

; 15   : }

	ret	0
?setFeedback@AllPassFilter@@QEAAXM@Z ENDP		; AllPassFilter::setFeedback
_TEXT	ENDS
; Function compile flags: /Ogspy
; File C:\Users\RenatoVolpe\personal\fox-suite-blocks\src\AllPassFilter.cpp
; File C:\Users\RenatoVolpe\personal\fox-suite-blocks\src\Delay.cpp
; File C:\Users\RenatoVolpe\personal\fox-suite-blocks\src\AllPassFilter.cpp
; File C:\Users\RenatoVolpe\personal\fox-suite-blocks\src\Delay.cpp
; File C:\Users\RenatoVolpe\personal\fox-suite-blocks\src\AllPassFilter.cpp
; File C:\Users\RenatoVolpe\personal\fox-suite-blocks\src\Delay.cpp
; File C:\Users\RenatoVolpe\personal\fox-suite-blocks\src\AllPassFilter.cpp
;	COMDAT ?processAudio@AllPassFilter@@UEAAMM@Z
_TEXT	SEGMENT
this$ = 48
xn$ = 56
?processAudio@AllPassFilter@@UEAAMM@Z PROC		; AllPassFilter::processAudio, COMDAT

; 27   : float AllPassFilter::processAudio(float xn) {

$LN10:
	sub	rsp, 40					; 00000028H

; 33   : 	float yn = buf - ap_feedbackGain * xn;

	movss	xmm5, DWORD PTR [rcx+56]
	movaps	xmm4, xmm1
	mov	r9, rcx
	call	?readFromDelayLine@Delay@@QEAAMXZ	; Delay::readFromDelayLine
; File C:\Users\RenatoVolpe\personal\fox-suite-blocks\src\Delay.cpp

; 176  : 	dly_buffer[dly_writeIndex] = xn;

	movsxd	rcx, DWORD PTR [r9+32]
; File C:\Users\RenatoVolpe\personal\fox-suite-blocks\src\AllPassFilter.cpp

; 33   : 	float yn = buf - ap_feedbackGain * xn;

	movaps	xmm3, xmm5
; File C:\Users\RenatoVolpe\personal\fox-suite-blocks\src\Delay.cpp

; 176  : 	dly_buffer[dly_writeIndex] = xn;

	mov	rax, QWORD PTR [r9+40]

; 162  : 	if (dly_readIndex >= dly_lineLengthInSamples)

	xor	edx, edx
; File C:\Users\RenatoVolpe\personal\fox-suite-blocks\src\AllPassFilter.cpp

; 33   : 	float yn = buf - ap_feedbackGain * xn;

	mulss	xmm3, xmm4
	subss	xmm0, xmm3

; 34   : 
; 35   : 	// define sample to be written to delay line
; 36   : 	float samp = xn + ap_feedbackGain * yn;

	mulss	xmm5, xmm0
	addss	xmm5, xmm4
; File C:\Users\RenatoVolpe\personal\fox-suite-blocks\src\Delay.cpp

; 176  : 	dly_buffer[dly_writeIndex] = xn;

	movss	DWORD PTR [rax+rcx*4], xmm5

; 159  : 	dly_readIndex++;

	inc	DWORD PTR [r9+28]

; 160  : 
; 161  : 	// check if reading index is out of delay line length
; 162  : 	if (dly_readIndex >= dly_lineLengthInSamples)

	mov	ecx, DWORD PTR [r9+12]
	cmp	DWORD PTR [r9+28], ecx
	jl	SHORT $LN6@processAud

; 163  : 		dly_readIndex = 0;

	mov	DWORD PTR [r9+28], edx
$LN6@processAud:

; 164  : 
; 165  : 	// Increase writing index
; 166  : 	dly_writeIndex++;

	inc	DWORD PTR [r9+32]

; 167  : 
; 168  : 	// check if writing index is out of delay line length
; 169  : 	if (dly_writeIndex >= dly_lineLengthInSamples)

	mov	eax, DWORD PTR [r9+32]
	cmp	eax, ecx
	cmovge	eax, edx
	mov	DWORD PTR [r9+32], eax
; File C:\Users\RenatoVolpe\personal\fox-suite-blocks\src\AllPassFilter.cpp

; 46   : }

	add	rsp, 40					; 00000028H
	ret	0
?processAudio@AllPassFilter@@UEAAMM@Z ENDP		; AllPassFilter::processAudio
_TEXT	ENDS
END
