; Listing generated by Microsoft (R) Optimizing Compiler Version 19.29.30145.0 

include listing.inc

INCLUDELIB OLDNAMES

PUBLIC	??_R4Tremolo@@6B@				; Tremolo::`RTTI Complete Object Locator'
PUBLIC	??_R1A@?0A@EA@Tremolo@@8			; Tremolo::`RTTI Base Class Descriptor at (0,-1,0,64)'
PUBLIC	??_R3Tremolo@@8					; Tremolo::`RTTI Class Hierarchy Descriptor'
PUBLIC	??_7Tremolo@@6B@				; Tremolo::`vftable'
PUBLIC	??_R0?AVTremolo@@@8				; Tremolo `RTTI Type Descriptor'
PUBLIC	??_R2Tremolo@@8					; Tremolo::`RTTI Base Class Array'
;	COMDAT ??_R2Tremolo@@8
rdata$r	SEGMENT
??_R2Tremolo@@8 DD imagerel ??_R1A@?0A@EA@Tremolo@@8	; Tremolo::`RTTI Base Class Array'
	ORG $+3
rdata$r	ENDS
;	COMDAT ??_R0?AVTremolo@@@8
data$rs	SEGMENT
??_R0?AVTremolo@@@8 DQ FLAT:??_7type_info@@6B@		; Tremolo `RTTI Type Descriptor'
	DQ	0000000000000000H
	DB	'.?AVTremolo@@', 00H
data$rs	ENDS
;	COMDAT ??_7Tremolo@@6B@
CONST	SEGMENT
??_7Tremolo@@6B@ DQ FLAT:??_R4Tremolo@@6B@		; Tremolo::`vftable'
	DQ	FLAT:?processAudio@Tremolo@@UEAAMM@Z
	DQ	FLAT:?setSampleRate@Tremolo@@UEAAXH@Z
CONST	ENDS
;	COMDAT ??_R3Tremolo@@8
rdata$r	SEGMENT
??_R3Tremolo@@8 DD 00H					; Tremolo::`RTTI Class Hierarchy Descriptor'
	DD	00H
	DD	01H
	DD	imagerel ??_R2Tremolo@@8
rdata$r	ENDS
;	COMDAT ??_R1A@?0A@EA@Tremolo@@8
rdata$r	SEGMENT
??_R1A@?0A@EA@Tremolo@@8 DD imagerel ??_R0?AVTremolo@@@8 ; Tremolo::`RTTI Base Class Descriptor at (0,-1,0,64)'
	DD	00H
	DD	00H
	DD	0ffffffffH
	DD	00H
	DD	040H
	DD	imagerel ??_R3Tremolo@@8
rdata$r	ENDS
;	COMDAT ??_R4Tremolo@@6B@
rdata$r	SEGMENT
??_R4Tremolo@@6B@ DD 01H				; Tremolo::`RTTI Complete Object Locator'
	DD	00H
	DD	00H
	DD	imagerel ??_R0?AVTremolo@@@8
	DD	imagerel ??_R3Tremolo@@8
	DD	imagerel ??_R4Tremolo@@6B@
PUBLIC	?setSampleRate@Tremolo@@UEAAXH@Z		; Tremolo::setSampleRate
PUBLIC	?processAudio@Tremolo@@UEAAMM@Z			; Tremolo::processAudio
PUBLIC	??1Tremolo@@QEAA@XZ				; Tremolo::~Tremolo
;	COMDAT pdata
pdata	SEGMENT
$pdata$?processAudio@Tremolo@@UEAAMM@Z DD imagerel $LN4
	DD	imagerel $LN4+85
	DD	imagerel $unwind$?processAudio@Tremolo@@UEAAMM@Z
;	COMDAT xdata
xdata	SEGMENT
$unwind$?processAudio@Tremolo@@UEAAMM@Z DD 040e01H
	DD	02680eH
	DD	030025206H
; Function compile flags: /Ogspy
; File C:\Users\RenatoVolpe\personal\fox-suite-blocks\src\Tremolo.cpp
;	COMDAT ??1Tremolo@@QEAA@XZ
_TEXT	SEGMENT
this$ = 8
??1Tremolo@@QEAA@XZ PROC				; Tremolo::~Tremolo, COMDAT

; 11   : Tremolo::~Tremolo() {

	lea	rax, OFFSET FLAT:??_7Tremolo@@6B@
	mov	QWORD PTR [rcx], rax
	mov	rcx, QWORD PTR [rcx+24]
	jmp	??1LFO@@QEAA@XZ				; LFO::~LFO
??1Tremolo@@QEAA@XZ ENDP				; Tremolo::~Tremolo
_TEXT	ENDS
; Function compile flags: /Ogspy
; File C:\Users\RenatoVolpe\personal\fox-suite-blocks\src\Tremolo.cpp
;	COMDAT ?processAudio@Tremolo@@UEAAMM@Z
_TEXT	SEGMENT
this$ = 64
xn$ = 72
?processAudio@Tremolo@@UEAAMM@Z PROC			; Tremolo::processAudio, COMDAT

; 62   : {	

$LN4:
	push	rbx
	sub	rsp, 48					; 00000030H
	mov	rbx, rcx
	movaps	XMMWORD PTR [rsp+32], xmm6

; 63   : 	// Compute LFO value
; 64   : 	float lfoValue = trem_LFOOscillator->processAudio();

	mov	rcx, QWORD PTR [rcx+24]
	movaps	xmm6, xmm1
	mov	rax, QWORD PTR [rcx]
	call	QWORD PTR [rax+16]

; 65   : 
; 66   : 	// All Pass Filter processing
; 67   : 	return xn * lfoValue + xn * (0.99 - trem_modDepth);

	movsd	xmm4, QWORD PTR __real@3fefae147ae147ae
	xorps	xmm3, xmm3
	movss	xmm2, DWORD PTR [rbx+12]
	mulss	xmm0, xmm6
	cvtss2sd xmm3, xmm6

; 68   : }

	movaps	xmm6, XMMWORD PTR [rsp+32]
	cvtss2sd xmm0, xmm0
	cvtps2pd xmm2, xmm2
	subsd	xmm4, xmm2
	mulsd	xmm4, xmm3
	addsd	xmm4, xmm0
	cvtpd2ps xmm0, xmm4
	add	rsp, 48					; 00000030H
	pop	rbx
	ret	0
?processAudio@Tremolo@@UEAAMM@Z ENDP			; Tremolo::processAudio
_TEXT	ENDS
; Function compile flags: /Ogspy
; File C:\Users\RenatoVolpe\personal\fox-suite-blocks\src\Tremolo.cpp
;	COMDAT ?setSampleRate@Tremolo@@UEAAXH@Z
_TEXT	SEGMENT
this$ = 8
sampleRate$ = 16
?setSampleRate@Tremolo@@UEAAXH@Z PROC			; Tremolo::setSampleRate, COMDAT

; 72   : 	trem_LFOOscillator->setSampleRate(sampleRate);

	mov	rcx, QWORD PTR [rcx+24]
	mov	rax, QWORD PTR [rcx]
	rex_jmp	QWORD PTR [rax+8]
?setSampleRate@Tremolo@@UEAAXH@Z ENDP			; Tremolo::setSampleRate
_TEXT	ENDS
END
