; Listing generated by Microsoft (R) Optimizing Compiler Version 19.29.30133.0 

include listing.inc

INCLUDELIB OLDNAMES

PUBLIC	?mapValueIntoRange@@YAMMMM@Z			; mapValueIntoRange
; Function compile flags: /Ogspy
; File E:\FoxSuite\fox-suite-blocks\src\utils.cpp
;	COMDAT ?mapValueIntoRange@@YAMMMM@Z
_TEXT	SEGMENT
value$ = 8
minvalue$dead$ = 16
maxValue$dead$ = 24
?mapValueIntoRange@@YAMMMM@Z PROC			; mapValueIntoRange, COMDAT

; 5    :     return minvalue + value * (maxValue - minvalue);

	mulss	xmm0, DWORD PTR __real@46944800
	addss	xmm0, DWORD PTR __real@41a00000

; 6    : }

	ret	0
?mapValueIntoRange@@YAMMMM@Z ENDP			; mapValueIntoRange
_TEXT	ENDS
END
