; Listing generated by Microsoft (R) Optimizing Compiler Version 19.29.30133.0 

include listing.inc

INCLUDELIB OLDNAMES

PUBLIC	DllMain
PUBLIC	MAIN
PUBLIC	VSTPluginMain
;	COMDAT pdata
pdata	SEGMENT
$pdata$VSTPluginMain DD imagerel $LN12
	DD	imagerel $LN12+95
	DD	imagerel $unwind$VSTPluginMain
;	COMDAT xdata
xdata	SEGMENT
$unwind$VSTPluginMain DD 020601H
	DD	030025206H
; Function compile flags: /Ogspy
; File E:\FoxSuite\shimmer\vst-2.4-sdk\vstsdk2.4\public.sdk\source\vst2.x\vstplugmain.cpp
; File E:\FoxSuite\shimmer\Shimmer.cpp
; File E:\FoxSuite\shimmer\vst-2.4-sdk\vstsdk2.4\public.sdk\source\vst2.x\vstplugmain.cpp
;	COMDAT VSTPluginMain
_TEXT	SEGMENT
audioMaster$ = 64
VSTPluginMain PROC					; COMDAT

; 31   : {

$LN12:
	push	rbx
	sub	rsp, 48					; 00000030H

; 32   : 	// Get VST Version of the Host
; 33   : 	if (!audioMaster (0, audioMasterVersion, 0, 0, 0, 0))

	xor	r9d, r9d
	xorps	xmm0, xmm0
	mov	rbx, rcx
	movss	DWORD PTR [rsp+40], xmm0
	and	QWORD PTR [rsp+32], 0
	xor	r8d, r8d
	xor	ecx, ecx
	lea	edx, QWORD PTR [r9+1]
	call	rbx
	test	rax, rax
	je	SHORT $LN9@VSTPluginM
; File E:\FoxSuite\shimmer\Shimmer.cpp

; 90   :     return new Shimmer(audioMaster);

	mov	ecx, 344				; 00000158H
	call	??2@YAPEAX_K@Z				; operator new
	mov	rdx, rbx
	mov	rcx, rax
	call	??0Shimmer@@QEAA@P6A_JPEAUAEffect@@HH_JPEAXM@Z@Z ; Shimmer::Shimmer
; File E:\FoxSuite\shimmer\vst-2.4-sdk\vstsdk2.4\public.sdk\source\vst2.x\vstplugmain.cpp

; 38   : 	if (!effect)

	test	rax, rax
	je	SHORT $LN9@VSTPluginM

; 40   : 
; 41   : 	// Return the VST AEffect structur
; 42   : 	return effect->getAeffect ();

	mov	rdx, QWORD PTR [rax]
	mov	rcx, rax

; 43   : }

	add	rsp, 48					; 00000030H
	pop	rbx

; 40   : 
; 41   : 	// Return the VST AEffect structur
; 42   : 	return effect->getAeffect ();

	rex_jmp	QWORD PTR [rdx+240]
$LN9@VSTPluginM:

; 39   : 		return 0;

	xor	eax, eax

; 43   : }

	add	rsp, 48					; 00000030H
	pop	rbx
	ret	0
VSTPluginMain ENDP
_TEXT	ENDS
; Function compile flags: /Ogspy
; File E:\FoxSuite\shimmer\vst-2.4-sdk\vstsdk2.4\public.sdk\source\vst2.x\vstplugmain.cpp
;	COMDAT MAIN
_TEXT	SEGMENT
audioMaster$ = 8
MAIN	PROC						; COMDAT

; 49   : VST_EXPORT AEffect* MAIN (audioMasterCallback audioMaster) { return VSTPluginMain (audioMaster); }

	jmp	VSTPluginMain
MAIN	ENDP
_TEXT	ENDS
; Function compile flags: /Ogspy
; File E:\FoxSuite\shimmer\vst-2.4-sdk\vstsdk2.4\public.sdk\source\vst2.x\vstplugmain.cpp
;	COMDAT DllMain
_TEXT	SEGMENT
hInst$ = 8
dwReason$ = 16
lpvReserved$ = 24
DllMain	PROC						; COMDAT

; 64   : 	hInstance = hInst;
; 65   : 	return 1;

	mov	eax, 1

; 66   : }

	ret	0
DllMain	ENDP
_TEXT	ENDS
END
